# Generated by Django 4.1.2 on 2022-10-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('enroll_no', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('kurta', models.IntegerField()),
                ('pyjama', models.IntegerField()),
                ('shirt', models.IntegerField()),
                ('tshirt', models.IntegerField()),
                ('pant', models.IntegerField()),
                ('lower', models.IntegerField()),
                ('shorts', models.IntegerField()),
                ('bedsheet', models.IntegerField()),
                ('pillowcover', models.IntegerField()),
                ('towel', models.IntegerField()),
                ('dupatta', models.IntegerField()),
                ('total_clothes', models.IntegerField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
